import React from 'react';
import { ModuleData, GlossaryTerm, Reference, BriefNoteRow } from './types';
import { Tooltip } from './components/Tooltip';
import { PredictiveCodingDiagram, MotorFailureDiagram } from './components/Diagrams';
import { BeakerIcon, BrainIcon, ChartBarIcon, HeartIcon, PuzzleIcon, UsersIcon } from './components/Icons';

// --- GLOSSARY & CITATIONS ---

const GLOSSARY_TERMS: GlossaryTerm[] = [
  { term: "precision", definition: "In the Bayesian brain model, precision refers to the confidence or weight given to sensory information or prior beliefs. High-precision signals have a stronger influence on perception. Also referred to as attentional gain." },
  { term: "prediction error", definition: "The mismatch between what the brain predicts will happen and the actual sensory input it receives. The brain constantly works to minimize prediction error by updating its predictions or initiating actions." },
  { term: "prior beliefs", definition: "The brain's existing models or expectations about the world, based on past experiences. These 'priors' are used to generate predictions about incoming sensory information." },
  { term: "attentional gain/precision", definition: "Attention can increase the precision (or 'volume') of specific prior beliefs or sensory signals, making them more influential in shaping perception and action." },
  { term: "misattribution of agency", definition: "The experience of a movement or sensation as involuntary because it was not predicted by high-level conscious intentions, even though it was generated by the brain's own processes." },
  { term: "dissociation", definition: "From a modern predictive coding perspective, dissociation is not a 'split' but a state where high-precision prior beliefs override or block out actual sensory input, leading to a feeling of detachment or loss of function." },
];

const REFERENCES: Reference[] = [
  { key: "mavroudis2024", citation: "Mavroudis et al., 2024", full: "Mavroudis, I., Kazis, D., Kamal, F. Z., Gurzu, I.-L., Ciobica, A., Pădurariu, M., ... & Iordache, A. (2024). Understanding Functional Neurological Disorder: Recent Insights and Diagnostic Challenges. International Journal of Molecular Sciences, 25(8), 4470.", url: "https://doi.org/10.3390/ijms25084470" },
  { key: "edwards2012", citation: "Edwards et al., 2012", full: "Edwards, M. J., Adams, R. A., Brown, H., Pareés, I., & Friston, K. J. (2012). A Bayesian account of 'hysteria'. Brain, 135(11), 3495–3512.", url: "https://doi.org/10.1093/brain/aws129" },
  { key: "paredes2022", citation: "Paredes-Echeverri et al., 2022", full: "Paredes-Echeverri, S., Guthrie, A. J., & Perez, D. L. (2022). Toward a possible trauma subtype of functional neurological disorder: impact on symptom severity and physical health. Frontiers in Psychiatry, 13, 1040911.", url: "https://doi.org/10.3389/fpsyt.2022.1040911" },
];

const glossaryMap = new Map(GLOSSARY_TERMS.map(item => [item.term.toLowerCase(), item.definition]));
const referenceMap = new Map(REFERENCES.map(item => [item.key, item]));

const Citation = ({ source }: { source: string }) => {
  const ref = referenceMap.get(source);
  if (!ref) return null;
  return <a href={ref.url} target="_blank" rel="noopener noreferrer" className="text-brand-dark dark:text-brand-light text-xs align-super">({ref.citation})</a>;
};

const T = ({ children }: { children: string }) => {
  const definition = glossaryMap.get(children.toLowerCase());
  return definition ? <Tooltip tip={definition}>{children}</Tooltip> : <>{children}</>;
};

// --- MODULE CONTENT ---

export const MODULES_DATA: ModuleData[] = [
  {
    id: "module1",
    title: "Understanding FND: Introduction & Epidemiology",
    icon: <ChartBarIcon />,
    keyMessage: <>FND is common, real, and disabling for many people, with major personal and system-level impact <Citation source="mavroudis2024" />.</>,
    content: [
      <><strong>A Modern Diagnosis:</strong> FND is marked by neurological symptoms (e.g., weakness, tremors) diagnosed via "positive signs" that show inconsistency with known diseases. For therapists, these signs are key for psychoeducation, validating the patient's real experience, and distinguishing FND from feigning.</>,
      <><strong>From 'Hysteria' to Brain Science:</strong> The field has moved past outdated terms to a biopsychosocial model. FND is now seen as a multi-network brain disorder, bridging neurology and psychology.</>,
      <><strong>A Common Condition:</strong> FND is not rare. It's the second most frequent diagnosis in outpatient neurology clinics, affecting many and carrying a significant healthcare burden.</>,
      <><strong>Who Is Affected:</strong> FND can affect anyone, but it's diagnosed more often in women (~70%). While it can appear in childhood, it most commonly emerges in early to mid-adulthood.</>,
    ],
    caseApplication: {
      helper: [
        <>Your case: age/setting/symptoms →</>,
        <>Positive exam signs to highlight →</>,
        <>One sentence to validate and explain the diagnosis →</>,
      ],
      discussion: [
        { question: "How will you use positive signs to explain the diagnosis in your case and reduce self-doubt or stigma?" },
        { question: "What first-step plan will you offer (education + one practical skill) for the next visit?" }
      ]
    },
  },
  {
    id: "module2",
    title: "The Brain as a 'Prediction Machine'",
    icon: <BrainIcon />,
    keyMessage: <>Symptoms can arise when strong expectations (<T>prior beliefs</T>) get too much <T>precision</T> (helped by attention), so they outweigh real sensory input; higher-level plans didn’t intend this, so it feels involuntary (<T>misattribution of agency</T>) <Citation source="edwards2012" />.</>,
    diagram: <PredictiveCodingDiagram />,
    content: [
      <><strong>Plain explanation:</strong> The brain predicts, compares with senses, and updates. <T>Precision</T> is the “volume knob” on predictions or sensory input, and attention can turn that knob. If the knob favors the wrong expectation, the body may act as if that expectation is true.</>,
      <><strong>Clinical links:</strong> Brief, plain-language explanation; CBT to test and update expectations; attention training; graded motor tasks that lean into accurate sensory feedback.</>,
    ],
    caseApplication: {
      helper: [
        <>Likely “sticky expectations” in your case →</>,
        <>Attention traps (times/places symptoms spike) →</>,
        <>One practice to shift precision toward helpful sensory cues →</>,
      ],
      discussion: [
        { question: "How will you explain precision and prediction error to your patient in 2 minutes, and what home practice will you pair with that story?" },
        { question: "What signs will tell you the practice is working (e.g., shorter episodes, steadier movement)?" }
      ]
    }
  },
  {
    id: "module3",
    title: "Where Do Symptoms Come From?",
    icon: <PuzzleIcon />,
    keyMessage: <>Background risks + triggers + thinking/feeling styles can shape strong expectations and attention, and sometimes create a perception from noise <Citation source="edwards2012" /><Citation source="mavroudis2024" />.</>,
    diagram: <MotorFailureDiagram />,
    content: [
        <><strong>Attention is a Key Lever:</strong> Symptoms are highly sensitive to attention. We see this in clinical signs like tremor entrainment or Hoover’s sign, where symptoms change or disappear when attention is diverted. This makes attention a powerful therapeutic tool.</>,
        <><strong>Beliefs Shape Reality:</strong> Strong expectations about illness, shaped by experience or culture, can become self-fulfilling prophecies. The brain 'finds' what it expects to find. The powerful response of FND to placebo is a clear example.</>,
        <><strong>Triggers Plant a Seed:</strong> A physical event like an injury, illness, or panic attack can create a durable, high-precision 'memory' or prediction in the brain, which can then be re-activated later as an FND symptom.</>,
        <><strong>Cognitive & Emotional Factors:</strong> Anxiety and depression can lower the threshold for symptoms. Thinking styles like catastrophizing or jumping to conclusions can 'lock in' a symptom by providing a compelling but incorrect explanation for it.</>,
    ],
    caseApplication: {
      helper: [
        <>Predisposing → Trigger → Maintaining loops for your case →</>,
        <>One belief or habit to target first →</>,
        <>Safety plan for high-attention situations →</>,
      ],
      discussion: [
        { question: "What three loops keep symptoms going in your case, and how will you break one loop this week?" },
        { question: "How will you measure change that the patient will notice?" }
      ]
    }
  },
   {
    id: "module4",
    title: "Trauma-Linked Patterns",
    icon: <HeartIcon />,
    keyMessage: <>A trauma-linked subtype may exist: more adverse life experiences and probable PTSD are tied to higher symptom severity and worse physical health <Citation source="paredes2022" />.</>,
    content: [
        <><strong>A Strong Connection:</strong> Individuals with FND report about three times more adverse life experiences (ALEs) than control groups, and higher ALEs often correlate with more severe FND symptoms.</>,
        <><strong>Impact of PTSD/Abuse:</strong> The subgroup of patients with probable PTSD or a history of abuse tends to report more severe symptoms and poorer physical health, suggesting a clinically distinct pattern.</>,
        <><strong>Neurobiological Basis:</strong> This link is reflected in the brain. FND patients with trauma histories show structural and functional connectivity differences in networks involving the amygdala, insula, and hippocampus—areas crucial for threat processing and memory.</>,
    ],
    caseApplication: {
      helper: [
        <>Trauma/ALE screen highlights →</>,
        <>Stabilization needs (sleep, safety, emotion skills) →</>,
        <>If PTSD present: candidate therapy (e.g., PE/DBT/EMDR) + timing →</>,
      ],
      discussion: [
        { question: "How would you phase care for a trauma-salient FND case (stabilize → trauma work → consolidation) while keeping FND education and motor retraining active?" },
        { question: "What risks would make you slow down or change order?" }
      ]
    }
  },
  {
    id: "module5",
    title: "What Imaging Tells Us",
    icon: <BeakerIcon />,
    keyMessage: <>FND is a disorder of brain network **function**, not structural damage. Imaging reveals altered connectivity in key pathways, providing a biological rationale for symptoms and a hopeful message for patients <Citation source="mavroudis2024" />.</>,
    content: [
      <><strong>Limbic & Salience Networks (Emotion-Motor Link):</strong> Studies show heightened activity in the amygdala and insula (the brain's emotion and body-state centers) and increased connectivity with motor control areas. This provides a direct biological link for how emotional states can influence physical symptoms.</>,
      <><strong>Self-Agency Networks (The "Involuntary" Feeling):</strong> Altered activity in regions like the right temporoparietal junction (rTPJ) is linked to a disrupted sense of agency. This helps explain why movements and symptoms feel like they are "happening to" the person, rather than being self-generated.</>,
      <><strong>Attentional & Sensorimotor Networks (Integration Issues):</strong> The brain's attentional circuits (including the cingulate gyrus) show dysregulation. This disrupts the normal integration of sensory information, emotional processing, and motor commands, contributing to the wide range of FND symptoms.</>,
      <><strong>Clinical Relevance & Future Hope:</strong> This network-based understanding is powerful for psychoeducation. Furthermore, early research suggests baseline brain activity might predict who responds best to CBT or motor retraining, pointing toward future personalized treatments.</>,
    ],
    caseApplication: {
      helper: [
        <>One imaging-informed sentence you’d use to validate the diagnosis →</>,
        <>Expectation-setting line about variability/recovery →</>,
      ],
      discussion: [
        { question: "How will you use this 'multi-network' idea to explain that symptoms are real and changeable?" },
        { question: "What goal would you set for the next two weeks that ties to this story?" }
      ]
    }
  },
  {
    id: "module6",
    title: "Clinical Implications & Team-Based Care",
    icon: <UsersIcon />,
    keyMessage: <>Effective treatment is multidisciplinary and psychologically-informed, using the therapeutic alliance to deliver psychoeducation and targeted interventions that retrain brain patterns <Citation source="mavroudis2024" /><Citation source="paredes2022" />.</>,
    content: [
        <><strong>Key Therapeutic Approaches for Psychologists:</strong></>,
        <ul className="list-none pl-4 space-y-2 -ml-3">
            <li><strong>Cognitive Behavioral Therapy (CBT):</strong> The primary evidence-based approach. Helps patients identify and restructure maladaptive <T>prior beliefs</T> about symptoms, test predictions through behavioral experiments, and retrain attentional patterns.</li>
            <li><strong>Mindfulness & Attention Training:</strong> Directly targets the mechanism of <T>attentional gain/precision</T>. Teaches patients to observe sensations without judgment and consciously redirect focus, weakening the link between attention and symptom generation.</li>
            <li><strong>Trauma-Informed Care:</strong> For patients in the trauma subtype, therapies like Prolonged Exposure (PE), EMDR, or skills-based approaches like Dialectical Behavior Therapy (DBT) can be critical for addressing underlying drivers of dysregulation <Citation source="paredes2022" />.</li>
        </ul>,
        <><strong>The Power of Psychoeducation:</strong> A clear, non-blaming explanation of the predictive coding model is a powerful intervention in itself. It validates the patient's experience, reduces stigma, and provides a hopeful, actionable framework for change.</>,
        <><strong>An Integrated Team:</strong> Psychologists are crucial partners with neurologists, physical therapists (PT), and occupational therapists (OT). Close collaboration ensures a consistent message and a holistic plan that addresses mind and body simultaneously.</>,
    ],
    caseApplication: {
      helper: [
        <>Two realistic goals for the next 2–4 weeks →</>,
        <>Team roles and hand-offs for this case →</>,
        <>One barrier (stigma, access, beliefs) + your plan to address it →</>,
      ],
      discussion: [
        { question: "How will you structure the next month for this person (visits, skills practice, PT/OT steps)?" },
        { question: "What language will you use to validate their experience while inviting them into an active plan?" }
      ]
    }
  }
];

// --- BRIEF NOTE & RESOURCES ---

export const BRIEF_NOTE_DATA: BriefNoteRow[] = [
    { aspect: "Presentation", fnd: "Inconsistent with known disease patterns, variable, distractible.", feigning: "Often simulates a known disease; may be overly consistent or dramatic." },
    { aspect: "Motivation", fnd: "Symptoms are not intentionally produced; secondary gain is not the driver.", feigning: "Symptoms are intentionally produced for a tangible external benefit (e.g., financial, avoiding responsibility)." },
    { aspect: "Brain Findings", fnd: "Altered network function (e.g., limbic-motor connectivity).", feigning: "Activation patterns suggest active mimicry, not genuine symptom experience." },
    { aspect: "Voluntariness", fnd: "Involuntary. Experienced as happening *to* the person.", feigning: "Voluntary. Done *by* the person, though they deny it." },
    { aspect: "Treatment Response", fnd: "Can improve with specific therapies (PT, CBT) that retrain brain patterns.", feigning: "Symptoms may cease when the external incentive is removed." },
];

export const ALL_REFERENCES = REFERENCES;